
general.import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Argonaut.toml",
  "/home/abdou/.config/alacritty/fonts.toml"
]
general.live_config_reload = true

[cursor]
unfocused_hollow = false

  [cursor.style]
  blinking = "On"
  shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

  [window.dimensions]
  columns = 82
  lines = 24

  [window.padding]
  x = 5
  y = 3
